# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-19 19:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_twork'),
    ]

    operations = [
        migrations.CreateModel(
            name='FContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_id', models.IntegerField(default=0)),
                ('content_type', models.IntegerField(default=0)),
                ('content_link', models.CharField(max_length=250)),
                ('content_youtube', models.CharField(max_length=250)),
                ('content_file', models.FileField(upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='FWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('teacher_id', models.IntegerField(default=0)),
                ('classroom_id', models.IntegerField(default=0)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
