# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-19 19:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_fcontent_fwork'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fcontent',
            old_name='work_id',
            new_name='forum_id',
        ),
    ]
