# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-19 20:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_auto_20170620_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcontent',
            name='content_file',
            field=models.FileField(blank=True, default='', upload_to=b''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fcontent',
            name='content_link',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='fcontent',
            name='content_youtube',
            field=models.CharField(blank=True, default=datetime.datetime(2017, 6, 19, 20, 17, 24, 864729, tzinfo=utc), max_length=250),
            preserve_default=False,
        ),
    ]
