# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-19 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_auto_20170620_0417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcontent',
            name='content_file',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='fcontent',
            name='content_link',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='fcontent',
            name='content_youtube',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
