# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-19 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_auto_20170620_0436'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcontent',
            name='content_title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
