# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-19 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0008_fcontent_content_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcontent',
            name='content_filename',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
