# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-19 09:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_assistant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swork',
            name='help',
        ),
    ]
