# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-19 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_remove_swork_help'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swork',
            name='youtube',
            field=models.CharField(max_length=100),
        ),
    ]
