# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-19 21:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20170619_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='SFWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(default=0)),
                ('index', models.IntegerField()),
                ('memo', models.TextField(default=b'')),
                ('publication_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('score', models.IntegerField(default=-1)),
                ('scorer', models.IntegerField(default=0)),
            ],
        ),
    ]
